---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/mclark4386/dotfiles-1.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
#   - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - zsh-history-substring-search
  #added mine:
  - molten-vk
  - rtmpdump
  - rustup-init
  - ncurses
  - scons
  - git-lfs
  - ninja
  - node@10
  - speex
  - boost
  - gnupg
  - node@12
  - node@14
  - buffalo
  - go-task
  - odin
  - terraform
  - ca-certificates
  - theora
  - lame
  - tinc
  - clisp
  - tor
  - cmake
  - openexr
  - cocoapods
  - openfortivpn
  - unrar
  - coreutils
  - unzip
  - deno
  - vala
  - dmd
  - dmg2img
  - webp
  - wget
  - libimobiledevice
  - wtfutil
  - dub
#   - handbrake
  - pianobar
  - x264
  - elm
  - x265
  - emacs
  - exercism
  - htop
  - llvm
  - pkg-config
  - faad2
  - hwloc
#   - postgresql
  - xterm
  - ffmpeg
  - lua@5.1
  - protobuf
  - xvid
  - ideviceinstaller
  - pwntools
  - xz
  - flac
  - libogg
  - lzo
  - youtube-dl
  - python
  - zeromq
  - mad
  - ios-deploy
  - maven
  - qemu
  - gatsby-cli
  - minetest
  - ranger
  - gcc
  - minicom
  - minikube

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  #added mine:
  - gobuffalo/tap
  - wtfutil/wtfutil
  - homebrew/cask-fonts
  - go-task/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
#   - dropbox
#   - firefox
  - google-chrome
  - handbrake
  - licecap
#   - sequel-ace
  - slack
#   - sublime-text
  - transmit
  - vagrant
  #added mine:
  - docker-compose
  - dbeaver-community
  - ghidra
  - inkscape
  - ltspice
  - perforce
  - arduino
  - detectx-swift
  - gimp
  - meld
  - discord
  - godot
  - jd-gui
  - vlc
  - dotnet-sdk
  - graphiql
  - kdiff3
  - netron
  - runjs
  - weka
  - blender
  - font-fira-code
  - krita
  - obs
  - thonny
  - fritzing
  - hermes
  - libreoffice
  - olive
  - twine
  - wireshark

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

#commenting this part until I am sure I want all those changes
# osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
# sublime_base_path: '~/Library/Application Support/Sublime Text'
# sublime_config_path: "Packages/User"
# sublime_package_control:
#   - "DocBlockr"
#   - "Dockerfile Syntax Highlighting"
#   - "FileDiffs"
#   - "GitHub Flavored Markdown Preview"
#   - "Jinja2"
#   - "Package Control"
#   - "PHP-Twig"
#   - "Pretty JSON"
#   - "SublimeLinterß
#   - "SublimeLinter-contrib-yamllint"
#   - "TrailingSpaces"
#   - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
